name:                Beanstalkd
version:             0.1.0.0
github:              "iazel/beanstalkd-hs"
license:             BSD3
author:              "Salvatore Pelligra"
maintainer:          "pelligra.s@gmail.com"
copyright:           "2018 Salvatore Pelligra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Beanstalkd client
category:            Client

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iazel/beanstalkd-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring == 0.10.*
- network == 2.6.*
- attoparsec == 0.13.*
- time-units
- aeson == 1.3.*
- yaml == 0.8.*
- text == 1.2.*

library:
  source-dirs: src

executables:
  Beanstalkd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Beanstalkd

tests:
  Beanstalkd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Beanstalkd
